galaxy_info:
  author: Yang Jun
  description: Install initializtion Software
  license: MIT
  min_ansible_version: 1.6
  platforms:
  - name: RedHat
    versions:
    - 6
  categories:
  - system
dependencies: []
