// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MachineStatProto struct {
	Innerip              *string  `protobuf:"bytes,1,opt,name=innerip" json:"innerip,omitempty"`
	Publicip             *string  `protobuf:"bytes,2,opt,name=publicip" json:"publicip,omitempty"`
	Cpu                  *string  `protobuf:"bytes,3,opt,name=cpu" json:"cpu,omitempty"`
	Mem                  *string  `protobuf:"bytes,4,opt,name=mem" json:"mem,omitempty"`
	Disk                 *string  `protobuf:"bytes,5,opt,name=disk" json:"disk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MachineStatProto) Reset()         { *m = MachineStatProto{} }
func (m *MachineStatProto) String() string { return proto.CompactTextString(m) }
func (*MachineStatProto) ProtoMessage()    {}
func (*MachineStatProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_47fac4216cce3615, []int{0}
}
func (m *MachineStatProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MachineStatProto.Unmarshal(m, b)
}
func (m *MachineStatProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MachineStatProto.Marshal(b, m, deterministic)
}
func (dst *MachineStatProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MachineStatProto.Merge(dst, src)
}
func (m *MachineStatProto) XXX_Size() int {
	return xxx_messageInfo_MachineStatProto.Size(m)
}
func (m *MachineStatProto) XXX_DiscardUnknown() {
	xxx_messageInfo_MachineStatProto.DiscardUnknown(m)
}

var xxx_messageInfo_MachineStatProto proto.InternalMessageInfo

func (m *MachineStatProto) GetInnerip() string {
	if m != nil && m.Innerip != nil {
		return *m.Innerip
	}
	return ""
}

func (m *MachineStatProto) GetPublicip() string {
	if m != nil && m.Publicip != nil {
		return *m.Publicip
	}
	return ""
}

func (m *MachineStatProto) GetCpu() string {
	if m != nil && m.Cpu != nil {
		return *m.Cpu
	}
	return ""
}

func (m *MachineStatProto) GetMem() string {
	if m != nil && m.Mem != nil {
		return *m.Mem
	}
	return ""
}

func (m *MachineStatProto) GetDisk() string {
	if m != nil && m.Disk != nil {
		return *m.Disk
	}
	return ""
}

func init() {
	proto.RegisterType((*MachineStatProto)(nil), "pb.MachineStatProto")
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_server_47fac4216cce3615) }

var fileDescriptor_server_47fac4216cce3615 = []byte{
	// 135 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x6a, 0x60, 0xe4,
	0x12, 0xf0, 0x4d, 0x4c, 0xce, 0xc8, 0xcc, 0x4b, 0x0d, 0x2e, 0x49, 0x2c, 0x09, 0x00, 0x4b, 0x48,
	0x70, 0xb1, 0x67, 0xe6, 0xe5, 0xa5, 0x16, 0x65, 0x16, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06,
	0xc1, 0xb8, 0x42, 0x52, 0x5c, 0x1c, 0x05, 0xa5, 0x49, 0x39, 0x99, 0xc9, 0x99, 0x05, 0x12, 0x4c,
	0x60, 0x29, 0x38, 0x5f, 0x48, 0x80, 0x8b, 0x39, 0xb9, 0xa0, 0x54, 0x82, 0x19, 0x2c, 0x0c, 0x62,
	0x82, 0x44, 0x72, 0x53, 0x73, 0x25, 0x58, 0x20, 0x22, 0xb9, 0xa9, 0xb9, 0x42, 0x42, 0x5c, 0x2c,
	0x29, 0x99, 0xc5, 0xd9, 0x12, 0xac, 0x60, 0x21, 0x30, 0x1b, 0x10, 0x00, 0x00, 0xff, 0xff, 0x7e,
	0xf2, 0x56, 0x9a, 0x95, 0x00, 0x00, 0x00,
}
