// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server_op.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MachineStatProto struct {
	Cpu                  *string  `protobuf:"bytes,1,opt,name=cpu" json:"cpu,omitempty"`
	Mem                  *string  `protobuf:"bytes,2,opt,name=mem" json:"mem,omitempty"`
	Disk                 *string  `protobuf:"bytes,3,opt,name=disk" json:"disk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MachineStatProto) Reset()         { *m = MachineStatProto{} }
func (m *MachineStatProto) String() string { return proto.CompactTextString(m) }
func (*MachineStatProto) ProtoMessage()    {}
func (*MachineStatProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_op_1dfe1dafa9b3b895, []int{0}
}
func (m *MachineStatProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MachineStatProto.Unmarshal(m, b)
}
func (m *MachineStatProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MachineStatProto.Marshal(b, m, deterministic)
}
func (dst *MachineStatProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MachineStatProto.Merge(dst, src)
}
func (m *MachineStatProto) XXX_Size() int {
	return xxx_messageInfo_MachineStatProto.Size(m)
}
func (m *MachineStatProto) XXX_DiscardUnknown() {
	xxx_messageInfo_MachineStatProto.DiscardUnknown(m)
}

var xxx_messageInfo_MachineStatProto proto.InternalMessageInfo

func (m *MachineStatProto) GetCpu() string {
	if m != nil && m.Cpu != nil {
		return *m.Cpu
	}
	return ""
}

func (m *MachineStatProto) GetMem() string {
	if m != nil && m.Mem != nil {
		return *m.Mem
	}
	return ""
}

func (m *MachineStatProto) GetDisk() string {
	if m != nil && m.Disk != nil {
		return *m.Disk
	}
	return ""
}

type UpdateClientStatProto struct {
	WorkerId             *string           `protobuf:"bytes,1,opt,name=worker_id,json=workerId" json:"worker_id,omitempty"`
	MachineStatProto     *MachineStatProto `protobuf:"bytes,2,opt,name=machine_stat_proto,json=machineStatProto" json:"machine_stat_proto,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateClientStatProto) Reset()         { *m = UpdateClientStatProto{} }
func (m *UpdateClientStatProto) String() string { return proto.CompactTextString(m) }
func (*UpdateClientStatProto) ProtoMessage()    {}
func (*UpdateClientStatProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_op_1dfe1dafa9b3b895, []int{1}
}
func (m *UpdateClientStatProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateClientStatProto.Unmarshal(m, b)
}
func (m *UpdateClientStatProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateClientStatProto.Marshal(b, m, deterministic)
}
func (dst *UpdateClientStatProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateClientStatProto.Merge(dst, src)
}
func (m *UpdateClientStatProto) XXX_Size() int {
	return xxx_messageInfo_UpdateClientStatProto.Size(m)
}
func (m *UpdateClientStatProto) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateClientStatProto.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateClientStatProto proto.InternalMessageInfo

func (m *UpdateClientStatProto) GetWorkerId() string {
	if m != nil && m.WorkerId != nil {
		return *m.WorkerId
	}
	return ""
}

func (m *UpdateClientStatProto) GetMachineStatProto() *MachineStatProto {
	if m != nil {
		return m.MachineStatProto
	}
	return nil
}

func init() {
	proto.RegisterType((*MachineStatProto)(nil), "pb.MachineStatProto")
	proto.RegisterType((*UpdateClientStatProto)(nil), "pb.UpdateClientStatProto")
}

func init() { proto.RegisterFile("server_op.proto", fileDescriptor_server_op_1dfe1dafa9b3b895) }

var fileDescriptor_server_op_1dfe1dafa9b3b895 = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0x8a, 0xcf, 0x2f, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52,
	0xf2, 0xe2, 0x12, 0xf0, 0x4d, 0x4c, 0xce, 0xc8, 0xcc, 0x4b, 0x0d, 0x2e, 0x49, 0x2c, 0x09, 0x00,
	0x8b, 0x0b, 0x70, 0x31, 0x27, 0x17, 0x94, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0x98,
	0x20, 0x91, 0xdc, 0xd4, 0x5c, 0x09, 0x26, 0x88, 0x48, 0x6e, 0x6a, 0xae, 0x90, 0x10, 0x17, 0x4b,
	0x4a, 0x66, 0x71, 0xb6, 0x04, 0x33, 0x58, 0x08, 0xcc, 0x56, 0xaa, 0xe0, 0x12, 0x0d, 0x2d, 0x48,
	0x49, 0x2c, 0x49, 0x75, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0x41, 0x18, 0x28, 0xcd, 0xc5, 0x59, 0x9e,
	0x5f, 0x94, 0x9d, 0x5a, 0x14, 0x9f, 0x99, 0x02, 0x35, 0x96, 0x03, 0x22, 0xe0, 0x99, 0x22, 0xe4,
	0xc4, 0x25, 0x94, 0x0b, 0x71, 0x41, 0x7c, 0x71, 0x49, 0x62, 0x49, 0x3c, 0xd8, 0x6d, 0x60, 0xab,
	0xb8, 0x8d, 0x44, 0xf4, 0x0a, 0x92, 0xf4, 0xd0, 0xdd, 0x17, 0x24, 0x90, 0x8b, 0x26, 0x02, 0x08,
	0x00, 0x00, 0xff, 0xff, 0xd9, 0x96, 0xd0, 0x61, 0xdb, 0x00, 0x00, 0x00,
}
